### ISSUE TITLE
[Question] Create a new entity without id and set it active

### ISSUE THREAD

**Issue by SteffenKoehler** [datorama/akita#318]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
First of all - great work what you have done here.
Background: We have a big application and are currently evaluating to switch to Akita. At the moment we are still using plain Redux. Aktia would do a lot of work for us, especially with the Entity Store. 

During the evaluation we encountered the following "problem":  

In our app we have a table with a list of entities. Clicking on an entity opens a sidebar with the details of that entity. These details can be changed and saved. We achieve this without any problems with the `setActive` function.
Now it is also possible to create a new entity. This is also displayed in the sidebar, but the input fields are empty to enter new values.

Here we would also like to work with the `setActive` function. The problem is that the new entity has no ID yet. If we assign a pseudo ID, the newly created entity is immediately displayed in the list. This should not be the case either. 

Do you have a best practice for such a case? So create a new entity without ID, edit it in a sidebar / detail view and only add it to the list when the user clicks on save. 

## Minimal reproduction of the problem with instructions
I have created a minimal Stackblitz example and hope to make it a little clearer. 
I created a comment in `todos.servie.ts`  where I think the magic should happen
https://stackblitz.com/edit/akita-example-cso9ti

**Comment by NetanelBasal** [comment]
And you need to persist the state of the **new** entity? So, if I type something, and close the sidebar, then I open it again, it should display the previous state?

**Comment by SteffenKoehler** [comment]
No. We have a mechanism that checks if the form is dirty and when closing the sidebar the user is notified that there are unsaved changes. 

When saving, a call is sent to the backend, which persists the data. 
The data in the table of course also comes from the backend

**Comment by NetanelBasal** [comment]
So, in that case, I would just create a simple condition in the `selectActive` observable. Something like:

```ts
this.selected$ = this.todosQuery.selectActive().pipe(map(active => {
   return active ? active : createEmptyEntity()
}))
```

**Comment by SteffenKoehler** [comment]
Then `selected$` is either an existing entity or the newly created one. But there is no longer the case 'nothing selected'. Or am I missing something? 

The sidebar is completely controlled by the table / list. If I select an element there, the sidebar is displayed on the right. I can deselect the element again and the sidebar is hidden. 
If I click on 'Create new element', the sidebar is also displayed. So the `selected$` controls the whole sidebar and the "nothing selected" state hides the sidebar. 

And thank you very much for your time and your answers, by the way.

**Comment by NetanelBasal** [comment]
Can you please join Akita's Gitter channel? It will be more comfortable to discuss there.

**Comment by SteffenKoehler** [comment]
Sure. I'm closing this.

**Comment by PaddingtonTheBear** [comment]
I've seen some discussion about this before, but what is the recommended approach for adding an entity to the store prior to it having a generated ID from the server? [This article is a good example](https://dev.to/arielgueta/introducing-one-to-many-relationship-in-angular-akita-37me), where prior to adding a new comment to the store, you have to wait to get a response from the server with an id. 

However, my use case is that I want to add a related sub-entity to my base entity store, update the new entity, and then persist it to my database. This doesn't work if I'm using ```setActive()```, since there isn't an id to find my entity anymore, and I don't want to have to create another store for my related entity.

The follow on discussion in gitter about this topic doesn't really give a clear answer to this situation. 

[Issue 53 talks about adding symbolic links](https://github.com/datorama/akita/pull/53), but I'm not sure if that really addresses this situation.

A workaround might be to use ```guid()``` to put a temporary id on the new entity until it is persisted, but then I have to delete the temporary id before sending to the server or modify my server to handle this. 

Would it make sense if Akita generated an internal guid() for all entities that it can use to find them prior to receiving the server generated id?

**Comment by NetanelBasal** [comment]
@PaddingtonTheBear you mean to maintain two different ids?

**Comment by PaddingtonTheBear** [comment]
> @PaddingtonTheBear you mean to maintain two different ids?

Nope, I would want the normal id that gets generated by the server to supersede the internal guid that Akita uses. I was thinking this might be a workaround for this situation where you have entities added to the store prior to them receiving server generated ids, so that you can still query and select these entities without ids. This feels a bit like a hack and I'm likely misunderstanding something.

When I update a sub-entity in my base store with ```arrayAdd```, how am I supposed to query the store again to retrieve it unless it has an ```id```? 

My use case mostly works because when I save my base entity, the my server returns a JSON response with generated ids for all my sub-entities, so the store gets updated then.

FYI, I'm using [NgEntityService](https://datorama.github.io/akita/docs/angular/entity-service) to reduce the need for manual HTTP requests.

Thank you for your response and help!

**Comment by NetanelBasal** [comment]
Any entity must have a persistent id. Imagine that you are subscribed to `selectEntity(id)`, and then you replace it.

**Comment by PaddingtonTheBear** [comment]
Understood that an entity must have an id, otherwise it wouldn't be possible to find it again in the store.

Apologies if I'm re-iterating the same point and example again, just trying to get clarity:

I'll use the example from my previous link that talks about stores for articles and comments. To keep it basic, I'll just focus on the articles store. Say I have a list of articles that is shown from a ```selectAll()``` query to the articles store. I want to add several new articles to my articles store without making a HTTP request to the server to generate an id. This works fine and they will show up in my list (as blank entries). 

However, obviously the edits I make to these new articles will not be reflected in the store because I don't have an id to update it with. So updating the store with my edits is not possible without an id that is either server or generated in the frontend? 

Shouldn't it be possible for Akita to have a temporary id for non-persisted entities that you can use to select it later? So if I do ```selectedEntity(id)``` and it doesn't detect an ```id``` on an entity in the store, it will look at the temporary id instead. This temporary id would get removed prior to sending the entity to the server.

**Comment by NetanelBasal** [comment]
And where you suggest storing this temporary id?

**Comment by PaddingtonTheBear** [comment]
Storing it directly on the entity that gets added to the store would be easiest, but dirty as you likely don't want Akita to be adding additional properties to entities that are being stored; they should probably remain pure.  

Maybe you could put entities without persisted ids into the ```ui``` store or some internal array with the temporary id and modify the queries to look there if no persisted id is detected, but then you would need to make sure things like ```selectAll()``` include these.

It's difficult, because when you add an entity to the store you're creating a new object which makes comparing by reference difficult...

**Comment by NetanelBasal** [comment]
It'll be difficult and error-prone. The best way I can think of right now is that if we support `idKey` callback:

```
@StoreConfig({
  idKey: entity => entity.id || entity.tempId
})
```

Then, when you send data to the server, you can create a general helper `withoutTempId(data)`

**Comment by PaddingtonTheBear** [comment]
That would work well, as it can re-use the logic already in place for using a different id property. 

Ideally it would be transparent to the Akita user, so they shouldn't have to maintain their own temporary ids or remove the temporary id when sending to the server, and it could just be a flag on the storeConfig to "enable temporary ids". 

I didn't want to have to modify the simplicity of NgEntityService to delete object properties prior to sending to the server, and realistically the server shouldn't care if there is a temp id added on anyways, so it isn't vital to remove the temp id prior to transmitting (unless we're talking about thousands / millions of requests, then the small increase could have some ramifications).

Understood about complexity of this though, so leaving it to the Akita user to implement that stuff isn't the biggest issue.

Thanks for looking into this again!

**Comment by kranthitechie** [comment]
An alternate approach could be to create a separate WIPStore to maintain records that are  not yet persisted. The selectors would get records from the EntityStore and the WIPStore. Inspired from this approach - https://redux.js.org/usage/structuring-reducers/normalizing-state-shape
