### ISSUE TITLE
Class Support missing from documentation

### ISSUE THREAD

**Issue by Sherloks** [datorama/akita#376]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

It seems that the "Class Support" section is missing from the lastest version documentation. There's no information about a change related to this in the CHANGELOG. 

Are you dropping support for class entities or it's just missing from the documentation?

**Comment by NetanelBasal** [comment]
We are not dropping the support, but it's not recommended to use it. You can see the docs [here](https://netbasal.gitbook.io/akita/v/3.11.0/general/class-support).

**Comment by rosostolato** [comment]
Hi @NetanelBasal I have some questions about class support...

I know that akita does not recommend using classes and when I was reading the reasons on docs I started to wonder why, so it says:

> We can’t store classes in the database. A typical example of this is when you need to save the store snapshot.

That's true. But when I use class, is akita saving to its store as a class or as a plain object? Does it have any conversion?

I'm asking because, if we could store data as plain object exporting it automatically when user add or update, it would have the same behaviour as if it was using only plain objects. And when user query for it, it can instantiate back to the class.

So for that we can have a base class that akita would know how to instantiate and serialize. eg:

```ts
export class AkitaModel<T> {
  // maybe constructor is not a good idea, we could move it to a static method
  // that way, user would be able to have his own constructor implementation with no big issues
  constructor(obj: Partial<T>): void {
     Object.assign(this, obj);
  }

  // it will return plain object
  toObject(): Partial<T> {
    return { ...this };
  }
}
```

user.model.ts
```ts
export class User extends AkitaModel {
  firstName: string;
  lastName: string;
  token: string;

  get name() {
    return `${this.firstName} ${this.lastName}`;
  }
}
```

So when user adds or updates, akita would call `toObject()` to get plaing object and, then when user query data, akita would call `new baseClass(data)`.

If a base class is not a good solution, maybe we can try decorators that attach these methods to the model. I believe that it would give great powers for akita users!

thanks!

**Comment by NetanelBasal** [comment]
> That's true. But when I use class, is Akita saving to its store as a class or as a plain object? Does it have any conversion?

It stores it as a class.

> We can't store classes in the database. A typical example of this is when you need to save the store snapshot.

You can use it. Before you update the store, you just need to turn it to an instance when you get it as plain objects from the server.

**Comment by rosostolato** [comment]
But what do you think about the solution I gave?

Because as I understand, it's easier to handle store with plain objects like it says here:
> 3. There are various third-party tools (for example immer) that only work with plain objects.

So the idea is to make akita able to handle conversions for the user... on that example you gave, once you set the `baseClass` for the store:

```ts
import { User } from './user.model';

@Injectable({ providedIn: 'root' })
@StoreConfig({
  name: 'Users',
  baseClass: User
})
export class UserStore extends EntityStore<UserState> {
  constructor() {
    super();
  }
}
```

it would handle class automatically, so user would be able to provide data directly in plain objects:
```ts
const entities = response; //.map(entity => new BaseClass(entity));
store.set(entities); // set plain objects
```

or instances:
```ts
const user = new User();
store.set(user); // set instance object
```

Anyway, akita would convert it to plain object to store and make it compatible with other tools and whatever, but then it would convert back to instance of `User` when someone query for it.

**Comment by NetanelBasal** [comment]
We need to test what is the performance cost we pay here.

**Comment by rosostolato** [comment]
You can count on me if need any help. I can try to implement something, but I need a while to learn how akita core works

**Comment by danzrou** [comment]
Personally to not overload Akita (due to performance and other costs) I have created an extension for Akita's entity query that transforms plain objects kept in the store into classes which in our case represent view models.

**Comment by rosostolato** [comment]
@danzrou cool! Could you share the link?

**Comment by danzrou** [comment]
https://gist.github.com/danzrou/6dcedcb483c4f0a900cfb6447710b307

**Comment by rosostolato** [comment]
> https://gist.github.com/danzrou/6dcedcb483c4f0a900cfb6447710b307

I liked it! Could you share the whole code? Why don't you wrap it in an npm package?
