### ISSUE TITLE
Custom Sorting with AkitaMatDataSource 

### ISSUE THREAD

**Issue by lilas78** [datorama/akita#581]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ x] Support request
[ ] Other... Please describe:
</code></pre>

## Question 

When using a MatDataSource, we have the possibility to customize the sorting by defining a "sortingDataAccessor" : this way, we can sort not on object attribute value, but on a custom computed value. This can be useful when a data column of a MatTable shows a computed value.
How can we accomplish this with a AkitaMatDataSource ?
With a AkitaMatDataSource, the sorting works great when the value of a column corresponds to an object attribute. But I don't find the way to define a sorting callback to customize the sorting behavior when the column value doesn't correspond to an object attribute.
Can you help ?

</code></pre>

**Comment by manudss** [comment]
Hello @lilas78 , 

AkitaMatDataSource is not part of Akita, it's a package created and maintained by a third party here: https://github.com/manudss/akita-filters-plugin, (occasionally, me). So it's better to create the issues in the github above. 

Indeed, there is no such feature sortingDataAccessor. It seems to me that when I started to create this library, this feature does not exist, or I was not aware of it.  
So I would have to look to align AkitaMatDataSource with MatDataSource. I probably won't have time to do it before next year. 


However, since AkitaMatDataSource is based on Akita, the spell used is the Akita one. And Akita's spell function accepts a function for the spell. So it is quite possible to use this function manually on your side, by calling the `setSortBy(order: SortByOptions)` function of AkitaFilterPlugins. 

SortByOptions is set by Akita here: https://datorama.github.io/akita/docs/entities/sorting/ 

For AkitaMatDataSource, in order to make it directly compatible, you could overload AkitaMatDataSource, in order to overload the method `set sort(sort: MatSort)`. In order to call for the interested columns the method setSortByOptions with a call back function. 
Something like that (not tested !). 
```typescript 
class CustomAkitaMatDataSource<S = any> extends AkitaMatDataSource<S> {     
     set sort(sort: MatSort) {
         if (/** test for colum you want**//) {
           this.akitaFiltersPlugin.setSortBy(//** your code for define custom sorting **/);
        } else {
            super.sort = sort;
         }
      }
   }
```

Afterwards, if you want to do a PR, to add this function "sortingDataAccessor", there is no problem. 

Hoping that it will help you, and don't hesitate to tell me, if needed, so that we can make the lib evolve.

Regards,

**Comment by lilas78** [comment]
OK, thank you so much for your answer. I will have a look at your suggestions.

Regards,
