### ISSUE TITLE
Add Release Notes to the Changelog

### ISSUE THREAD

**Issue by cshouts-tasc** [datorama/akita#759]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The changelog is not updated for every release.

## Expected behavior

The changelog contains information about what changed in each release.

## Minimal reproduction of the problem with instructions

Try to figure out what changes are included in the v6.2.4 release https://www.npmjs.com/package/@datorama/akita/v/6.2.4. There is no tag for it, and no mention of it in the changelog. It's not clear what branch the release was cut from. I'm not sure how a third party is supposed to find out what changed in this release.

## What is the motivation / use case for changing the behavior?

Build trust with the community by clearly documenting the changes in each release.

Others:
The changelog used to contain a complete log of all changes in each release. After the move to the monorepo structure on April 12, 2020 the changelog has been sparsely updated and no longer contains a complete version history. This has caused the team I work with to lose confidence in new releases of Akita.

**Comment by Den-dp** [comment]
I ended up here while looking "what's new in 6.2.4" since noticed that CHANGELOG.md was maintained by hand.

Tbh was surprised that akita doesn't have CHANGELOG.md auto-generation or auto-publishing Github Releases since to me it's de facto standard.

@NetanelBasal maybe we can contribute it? Any preferences on what tool to use?

**Comment by NetanelBasal** [comment]
https://github.com/jscutlery/semver

**Comment by Den-dp** [comment]
Ok, so after casual `ng add @jscutlery/semver` and trying out new `nx run akita:version` executor I found that it fails with 
```shell
Cannot read property 'root' of undefined
```
While digging into I found that *it looks like* since the latest `@jscutlery/semver` depends on the latest `@nrwl/devkit` - it is impossible to use it with the current outdated nx workspace.

So I tried to `nx migrate 11.6.3` (migrating on latest will bring angular 13 with its new APF and broken nx tooling, so I started with the latest 11), but after migration found that build-related tasks (I used those listed in CONTRIBUTING.md) failed with error:
```shell
libs/akita/src/lib/store.ts:48:14 - error NG2007: Class is using Angular features but is not decorated. Please add an explicit Angular decorator.

48 export class Store<S = any> {
                ~~~~~
```
so I added `@Injectable()` but after that, I stack on:
```shell
> nx run akita:build:production 
Building Angular Package

------------------------------------------------------------------------------
Building entry point '@datorama/akita'
------------------------------------------------------------------------------
× Compiling TypeScript sources through NGC
ERROR: C:/dev/akita/libs/akita/src/lib/store.ts:49:1: Error encountered in metadata generated for exported symbol 'Store': 
 C:/dev/akita/libs/akita/src/lib/store.ts:60:29: Metadata collected contains an error that will be reported at runtime: Could not resolve type Partial.
  {"__symbolic":"error","message":"Could not resolve type","line":59,"character":28,"context":{"typeName":"Partial"}}
C:/dev/akita/libs/akita/src/lib/store.ts:49:1: Error encountered in metadata generated for exported symbol 'Store': 
 C:/dev/akita/libs/akita/src/lib/store.ts:60:29: Metadata collected contains an error that will be reported at runtime: Could not resolve type Partial.
  {"__symbolic":"error","message":"Could not resolve type","line":59,"character":28,"context":{"typeName":"Partial"}}
```
In general, it seems to me difficult to do something while there is some technical debt.
But maybe I'm wrong and all that was needed was to find the proper version of `@jscutlery/semver` that is compatible with the current workspace.

**Comment by NetanelBasal** [comment]
We need to remove the `ngOnDestroy` method. It's a legacy method that shouldn't be there as it's not coupled to Angular.
